version: "1"
services:
  go-admin:
    build: .
    image: "github.com/shasw94/projX"
    ports:
      - "8888:8888"
    environment:
      DATABASE__HOST: "postgres"
    depends_on:
      - postgres
      - redis

    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
      volumes:
        - "./.storage/redis_data:/data"

