definitions:
  schema.BaseResponse:
    properties:
      code:
        type: string
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  schema.LoginBodyParams:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  schema.RefreshBodyParams:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  schema.RegisterBodyParams:
    properties:
      email:
        type: string
      password:
        type: string
      role_id:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: api login
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.LoginBodyParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.BaseResponse'
      summary: api login
      tags:
      - Auth
  /logout:
    post:
      consumes:
      - application/json
      description: api logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.BaseResponse'
      security:
      - ApiKeyAuth: []
      summary: api logout
      tags:
      - Auth
  /refresh:
    post:
      consumes:
      - application/json
      description: api refresh token
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.RefreshBodyParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.BaseResponse'
      summary: api refresh token
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: api register
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.RegisterBodyParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.BaseResponse'
      summary: api register
      tags:
      - Auth
swagger: "2.0"
